# Generated by Django 2.2.3 on 2019-07-05 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counts', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counts.Category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='name',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
